include:
    - project: "epi2melabs/ci-templates"
      file: "wf-containers.yaml"

variables:
    NF_WORKFLOW_OPTS: "--fastq test_data/sars-samples-demultiplexed/ --samples test_data/sample_sheet"


# pangolin to dockerhub, we don't expect to change this often so a simple manual build
release-pangolin:
    extends: .aux-container
    variables:
        AUX_IMAGE_NAME: "pangolin"
        AUX_IMAGE_ENVFILE: "environment_pangolin.yaml"


